theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false
auto-save = true
true-color = true
rulers = [100]
color-modes = true
cursorline = true
text-width = 100

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "file-modification-indicator", "file-name"]
center = []
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal.space]
"space" = "goto_word"

# TODO: wiki cmds in separate namespace
"n" = ":lsp-workspace-command zk.new -g journal"

[keys.normal.space.i]
c = ":toggle inline-diagnostics.cursor-line hint disable"
e = ":toggle end-of-line-diagnostics warning disable"
o = ":toggle inline-diagnostics.other-lines error disable"

# modifiers meaning:
# TODO: moving towards a different concept of modifiers. Establish a primary purpose for a key, then
# TODO: define alternate and control behaviors. This keeps similar meanings for modifiers, but avoids
# TODO: sticking keys on modifiers without a parent behavior
# Alt -> destructive modifier. Where there's a command than can optionally make changes or change 
#        register contents, alt enables the modification behavior
#           -> is this a smaller example of a broader pattern of alternative behavior?
#     -> shrink modifier. The same but smaller, opposite of Shift
# Shift -> reverse modifier. lowercase forwards, uppercase backwards
#       -> the same but bigger. ie word to WORD
# Ctrl -> movement modifier. Default interaction is with text (ie next match), ctrl makes these in terms
#           of cursor or picker movement
# TODO: comma is underused

[keys.normal]
A-w = "move_next_sub_word_start"
A-b = "move_prev_sub_word_start"
A-e = "move_next_sub_word_end"
A-d = "delete_selection"
d = "delete_selection_noyank"
A-c = "change_selection"
c = "change_selection_noyank"
x = "extend_to_line_bounds"
X = "extend_line"
J = "join_selections_space"
"A-x" = "shrink_to_line_bounds"
V = ["select_mode", "extend_to_line_end"]
"." = "repeat_last_motion"
# there's no repeat_last_insert command, this is accomplished through a code change
# "A-." = "repeat_last_insert"
"A-r" = "replace_with_yanked"
# TODO: copy to view and select modes
"C-j" = "page_cursor_half_down"
"C-k" = "page_cursor_half_up"
# TODO: jumplist movements seem random, but are muscle-memoried pretty well
# TODO: fast save history, save jump
"U" = "later"
"u" = "earlier"
"+" = "increment"
"minus" = "decrement"
"|" = "shell_pipe_to"
"A-|" = "shell_pipe"
"A-q" = "record_macro"
"q" = "replay_macro"
"'" = "select_register"
";" = ["keep_primary_selection", "collapse_selection"]
"_" = "trim_selections"
"A-l" = "select_next_sibling"
"A-h" = "select_prev_sibling"
"A-j" = "shrink_selection"
"A-k" = "expand_selection"
# TODO: yank join
# TODO: $ keep where exit is 0

# remove redundant keys/keys that use modifiers differently/unused keys as a simplification. This 
# breaks compatibility with docs, but trying to standardize and keep compatibility can't both work
"A-." = "no_op"
"C-u" = "no_op"
"C-d" = "no_op"
"C-s" = "no_op"
"home" = "no_op"
"end" = "no_op"
"C-a" = "no_op"
"C-x" = "no_op"
"G" = "no_op"
"A-`" = "no_op"

# I don't use ! and it doesn't quite fit with the Alt/Shift roles I've described. If
# I need these, then I'll revisit this change, likely by making | a minor mode
# This is pipe + prepend or append
"!" = "no_op"
"A-!" = "no_op"
"Q" = "no_op"
"S" = "no_op"
"A-s" = "no_op"
"A-minus" = "no_op"
"A-_" = "no_op"
"&" = "no_op" # pipe as filter
"A-;" = "no_op" # selection manipulation
"A-:" = "no_op"
"A-," = "no_op"
"A-C" = "no_op"
"(" = "no_op"
")" = "no_op"
"A-(" = "no_op"
"A-)" = "no_op"
"K" = "no_op"
"A-K" = "no_op"
"C-c" = "no_op"
"A-J" = "no_op"
"R" = "no_op"

[keys.select]
# movement commands within selections at "top level"
"A-w" = "extend_next_sub_word_start"
"A-b" = "extend_prev_sub_word_start"
"A-e" = "extend_next_sub_word_end"
"c" = "copy_selection_on_next_line"
"n" = "rotate_selections_forward"
"N" = "rotate_selections_backward"
"C" = "copy_selection_on_prev_line"
"d" = "remove_selections"
"D" = "remove_primary_selection"
x = "extend_to_line_bounds"
X = "extend_line"
";" = "collapse_selection"
# TODO: make flip selections available in normal mode
"~" = "flip_selections"
"=" = "align_selections"
# TODO: let these expand selection across siblings
"A-l" = "select_next_sibling"
"A-h" = "select_prev_sibling"
"A-j" = "shrink_selection"
"A-k" = "expand_selection"

[keys.select.space]
# TODO: ensure selections forward
"n" = "rotate_selections_forward"
"N" = "rotate_selections_backward"
"c" = "copy_selection_on_next_line"
"C" = "copy_selection_on_prev_line"
"k" = "keep_selections"
"K" = "keep_primary_selection"
"s" = "select_regex"
"S" = "split_selection"
"d" = "remove_selections"
"D" = "remove_primary_selection"
"j" = "save_selection"
";" = "collapse_selection"
"~" = "flip_selections"
"=" = "align_selections"
" " = "split_selection_on_newline"
"f" = "no_op"
"F" = "no_op"
"b" = "no_op"
"e" = "no_op"
"E" = "no_op"
"g" = "no_op"
"a" = "no_op"
"'" = "no_op"
"p" = "no_op"
"P" = "no_op"
"/" = "no_op"
"r" = "no_op"
"?" = "no_op"

[keys.normal."["]
"[" = "move_parent_node_start"

[keys.normal."]"]
"]" = "move_parent_node_end"
