[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 100
feature_words = false
feature_snippets = true
snippets_first = true
feature_unicode_input = false
feature_paths = false
snippets_global_scope_path = "~/.config/helix/snippets/global.toml"

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.pyrefly]
command = "pyrefly"
args = ["lsp"]

[language-server.ty]
command = "ty"
args = ["server"]

[language-server.pytest-language-server]
command = "pytest-language-server"

[[language]]
name = "python"
auto-format = true
roots = ["pyproject.toml"]
language-servers = ["ty", {name = "ruff", except-features = ["document-symbols", "workspace-symbols"]}, "scls"]

[[language]]
name = "markdown"
auto-format = true
language-servers = ["marksman", "scls"]

[language-server.chicken-lsp-server]
command = "chicken-lsp-server"

[[language]]
name = "scheme"
language-servers = ["chicken-lsp-server", "scls"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "scls"]

[[language]]
name = "xml"
formatter = { command = "tidy", args = ["-q", "-xml", "--show-errors", "0", "--show-warnings", "0", "--force-output", "--indent", "auto",  "--vertical-space", "yes", "--tidy-mark", "no", "-wrap", "120"] }

[[language]]
name = "html"
formatter = { command = "tidy", args = ["-q", "--show-errors", "0", "--show-warnings", "0", "--force-output", "--indent", "auto",  "--vertical-space", "yes", "--tidy-mark", "no", "-wrap", "120"] }
